### ISSUE TITLE
is dor-rights-auth still in use anywhere?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/infrastructure-team#7]
if not, amend the docs here: https://github.com/sul-dlss/infrastructure-team/blob/2f1b82dcceb7471c84b8cd4c894096888b120215/sdr/concepts_and_interactions.md?plain=1#L55

and move to sul-dlss-deprecated?

see https://github.com/sul-dlss/infrastructure-team/pull/6#discussion_r771427729

**Comment by mjgiarlo** [comment]
Yes, still used: https://github.com/search?q=org%3Asul-dlss+RightsAuth&type=code

Might be a different answer once we're fully Cocinized and post-Fedora.

**Comment by jcoyne** [comment]
I tend to look at https://github.com/sul-dlss/dor-rights-auth/network/dependents

**Comment by mjgiarlo** [comment]
That's a good view, too, but I've found false positives in that list before so if you care enough it can be worth verifying what it says.

**Comment by jcoyne** [comment]
Yeah, it seems to be "anything that has ever depended on it"
